# ######################################
# login api

# POST http://localhost:5000/api/auth/login
# Content-Type: application/json

# {
#  "email": "sonu@test.com",
#  "password": "123456"
# }

########    prduct iD ####


# GET http://localhost:5000/api/products

# POST http://localhost:5000/api/cart
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjJhZTJlZDAxOGE4ZmYyY2ZlNTQzMSIsImlhdCI6MTc3MzMzMzYyOSwiZXhwIjoxNzczOTM4NDI5fQ.pZjPYNVq0SX-4CiDnE--x1PSTOvGw2NmukvF1jBfb6Y
# Content-Type: application/json

# {
#  "productId": "69b2e678012b48a39392aa35",
#  "quantity": 1
# }

# POST http://localhost:5000/api/products
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjJhZTJlZDAxOGE4ZmYyY2ZlNTQzMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MzMzNzg2NCwiZXhwIjoxNzczOTQyNjY0fQ.2ly8JddAVmGfXTc_Et70J3xdLHyTqvNExOpzFTKryX4
# Content-Type: application/json

# {
#  "name": "Test Product",
#  "description": "Testing",
#  "price": 100,
#  "stock": 5
# }


GET http://localhost:5000/api/admin/stats
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YjJhZTJlZDAxOGE4ZmYyY2ZlNTQzMSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MzMzNzg2NCwiZXhwIjoxNzczOTQyNjY0fQ.2ly8JddAVmGfXTc_Et70J3xdLHyTqvNExOpzFTKryX4
